spring.application.name=pfe
spring.datasource.url=jdbc:postgresql://localhost:5432/pfe_db
spring.datasource.username=postgres
spring.datasource.password=ilhemboud05
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
spring.jwt.secret.key=mysecretkeysonelgaz@123!456!789!madebypfeproject@!
spring.jwt.date.expiration=86400000